# Generated by Django 3.0.2 on 2020-02-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200201_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
