# Generated by Django 3.0.2 on 2020-02-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200201_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='Type',
            new_name='typee',
        ),
    ]
