# Generated by Django 3.0.2 on 2020-02-01 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200201_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
