# Generated by Django 3.0.2 on 2020-02-01 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_startup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
