# Generated by Django 3.0.2 on 2020-02-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200202_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='project',
            new_name='news',
        ),
    ]
